[workspace]
name = "autowatchman"
authors = [
    "Katy Scott <bhklab.katyscott@gmail.com>",
    "Kaitlyn Kobayashi"
]
description = "AutoWATChmAN is a radiomics project in testicular cancer. "
license = "MIT"
channels = ["conda-forge", "bioconda"]
platforms = ["osx-arm64", "linux-64", "win-64", "osx-64"]
preview = ["pixi-build"]

[environments]
quality = { features = ["quality"], solve-group = "default" }
docs = { features = ["docs"], solve-group = "default" }
jarvais = {features = ["jarvais"], no-default-feature = true}

[activation]
# convenient variables which can be used in scripts
env.CONFIG = "${PIXI_PROJECT_ROOT}/config"
env.METADATA = "${PIXI_PROJECT_ROOT}/metadata"
env.LOGS = "${PIXI_PROJECT_ROOT}/logs"
env.RAWDATA = "${PIXI_PROJECT_ROOT}/data/rawdata"
env.PROCDATA = "${PIXI_PROJECT_ROOT}/data/procdata"
env.RESULTS = "${PIXI_PROJECT_ROOT}/data/results"
env.SCRIPTS = "${PIXI_PROJECT_ROOT}/workflow/scripts"

[dependencies]
python = "<3.13"
ipython = ">=9.13.0,<10"
ipykernel = ">=7.2.0,<8"
jupyterlab = ">=4.5.7,<5"
pip = ">=26.1.1,<27"
openpyxl = ">=3.1.5,<4"
pandas = ">=3.0.3,<4"
seaborn = ">=0.13.2,<0.14"
scikit-learn = ">=1.8.0,<2"

[pypi-dependencies]
damply = ">=0.26.1, <0.27"
med-imagetools = ">=1.2.0.2, <2"

[tasks]
example_script = {cmd="python $SCRIPTS/example_script.py", description="Run an example script"}

[feature.jarvais.dependencies]
python = "<3.13"
pip = ">=26.1.1,<27"
psutil = "7.0.0.*"
ipython = ">=9.13.0,<10"

[feature.jarvais.pypi-dependencies]
# jarvais = ">=0.21.0, <0.22"
damply = ">=0.26.1, <0.27"
jarvais = {path = "jarvais", editable = true}



############################################## QUALITY ###############################################
# Quality includes linting, type checking, and formatting
[feature.quality.dependencies]
ruff = ">=0.15.13,<0.16"

[feature.quality.tasks]
ruff-check.cmd = ["ruff", "check"]
ruff-check.inputs = ["config/ruff.toml", "workflow"]
ruff-check.description = "Run ruff check"

ruff-format.cmd = ["ruff", "format"]
ruff-format.inputs = ["config/ruff.toml", "workflow"]
ruff-format.depends-on = ["ruff-check"]
ruff-format.description = "Run ruff format, run check first"

qc.depends-on = ["ruff-format", "ruff-check"]
qc.description = "Quality check: ruff check and format"

############################################## DOCS ################################################

[feature.docs.dependencies]
mkdocs = ">=1.6.1,<2"
mkdocs-include-markdown-plugin = ">=7.2.0,<8"

[feature.docs.tasks.doc-build]
cmd = "mkdocs build -f mkdocs.yaml"
description = "Build documentation with mkdocs"

[feature.docs.tasks.doc-serve]
cmd = "mkdocs serve -f mkdocs.yaml"
depends-on = ["doc-build"]
description = "Serve documentation with mkdocs, runs doc-build first"
